# Site settings
title: erlendaakre.github.io
brief-intro: Scala developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://erlendaakre.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
twitter_username: erlendaakre
facebook_username: DELETE
github_username: erlendaakre
email: erlend@frostvoid.com
weibo_username: xxxxxxxx
zhihu_username: xxxxxxxxxxx
linkedIn_username: xxxxxxxxxx
dribbble_username:

description_footer: footer description TODO

# comments
disqus_shortname: erlendaakre

# statistics
google_analytics_id: #UA-00000

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
